version: "3"

networks:
  external_network:
  internal_network:
    internal: true

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal_network

  mongo:
    image: mongo
    restart: always
    networks:
      - internal_network
    volumes:
      - ./data/mongo:/data/db

  # elasticsearch:
  #   build: ./elasticsearch
  #   restart: always
  #   networks:
  #     - internal_network
  #   volumes:
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data
  #   environment:
  #     discovery.type: single-node
  #     bootstrap.memory_lock: "true"
  #     ES_JAVA_OPTS: -Xms256m -Xms256m

  crowi:
    image: crowi/crowi:1.7.9
    restart: always
    networks:
      - internal_network
    volumes:
      - ./data/crowi:/crowi/public/uploads
    environment:
      # DEBUG: "crowi:*"
      REDIS_URL: redis://redis:6379/crowi
      MONGO_URI: mongodb://mongo:27017/crowi
      # ELASTICSEARCH_URI: http://elasticsearch:9200/crowi
      FILE_UPLOAD: local
      MATHJAX: 1
    depends_on:
      - redis
      - mongo
      # - elasticsearch

  nginx:
    build: ./nginx
    restart: always
    networks:
      - external_network
      - internal_network
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - crowi
    ports:
      - 443:443
