networks:
  backend:
    name: backend
    external: true

services:
  redis:
    image: redis:7.0.11
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/redis:/data

  mongo:
    image: mongo:4.4.21
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/mongo:/data/db

  elasticsearch:
    image: ghcr.io/traptitech/es-with-sudachi:7.10.2-2.1.1-snapshot
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xms256m

  mysql:
    image: mariadb:10.0.19
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
