version: "3.9"

networks:
  backend:
    name: backend
    external: true

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/redis:/data

  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/mongo:/data/db

  elasticsearch:
    image: ghcr.io/traptitech/es-with-sudachi:7.10.2-2.1.1-snapshot
    restart: always
    networks:
      - backend
    volumes:
      - /var/opt/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xms256m
