version: "3.9"

networks:
  frontend:
    name: frontend
    external: true

services:
  nginx:
    build: ./nginx
    restart: always
    networks:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - 443:443
