version: "3.9"

networks:
  frontend:
    name: frontend
    external: true

services:
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /var/opt/ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
