networks:
  frontend:
    name: frontend
    external: true
  backend:
    name: backend
    external: true

services:
  traq:
    image: ghcr.io/traptitech/traq:3.15.0
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - /var/opt/data/traq:/app/storage
      - /var/opt/compose/traq/config.yml:/app/config.yml
      - /var/opt/compose/traq/ex-trap-firebase-admin-sdk-credential.json:/app/ex-trap-firebase-admin-sdk-credential.json
    environment:
      TRAQ_ORIGIN: https://q.ex.trap.jp
      TRAQ_MARIADB_HOST: mysql
      TRAQ_ES_URL: http://elasticsearch:9200
      TRAQ_PPROF: "false"
    expose:
      - "3000"
    command: serve

  traq-ui:
    image: ghcr.io/traptitech/traq-ui:3.17.4
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - traq
    volumes:
      - ./traq/frontend-override/:/app/override
    environment:
      APP_NAME: ex-traQ
