origin: "https://q.ex.trap.jp"
version: "ex-traq"
mariadb:
  host: "mysql"
  password: "password"
accessLog:
  enabled: false
gcp:
  serviceAccount:
    projectId: "ex-trap"
    file: "./ex-trap-firebase-admin-sdk-credential.json"
firebase:
  serviceAccount:
    file: "./ex-trap-firebase-admin-sdk-credential.json"
skyway:
  secretKey: "dummyToken"
externalAuth:
  slack:
    clientId: "535522054643.2065746016128"
    clientSecret: "dummyToken"
    allowSignUp: true
    allowedTeamId: "TFRFC1LJX"
es:
  url: http://elasticsearch:9200
  username: elastic
  password: "{{change this line}}"
