serviceAccount: "%s"

artifacts:
  objects:
    location: "%s/{{domain}}"
    paths:
      - "*.pem"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: sh
    args:
      - -c
      - |-
        gcloud secrets versions access latest --secret=zerossl-email > email
        gcloud secrets versions access latest --secret=zerossl-eab-kid > eab-kid
        gcloud secrets versions access latest --secret=zerossl-eab-hmac-key > eab-hmac-key

  - name: certbot/dns-google
    entrypoint: sh
    args:
      - -c
      - |-
        EMAIL=$$(cat email)
        EAB_KID=$$(cat eab-kid)
        EAB_HMAC_KEY=$$(cat eab-hmac-key)

        certbot certonly --non-interactive --dns-google \
        --server "https://acme.zerossl.com/v2/DV90" \
        --eab-kid "$$EAB_KID" --eab-hmac-key "$$EAB_HMAC_KEY" \
        --email "$$EMAIL" --agree-tos \
        --key-type ecdsa --elliptic-curve secp256r1 \
        --domains "{{domain}}" --domains "*.{{domain}}"

        cp -L /etc/letsencrypt/live/{{domain}}/*.pem .
