serviceAccount: "${service_account_id}"

artifacts:
  objects:
    location: "${bucket_url}/${domain}"
    paths:
      - "*.pem"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
    entrypoint: sh
    args:
      - -c
      - |-
        gcloud publicca external-account-keys create --format "value(.)" > publicca_external_account_keys

  - name: certbot/dns-google
    entrypoint: sh
    args:
      - -c
      - |-
        . publicca_external_account_keys

        certbot certonly --non-interactive --dns-google \
        --server "https://dv.acme-v02.api.pki.goog/directory" \
        --eab-kid "$$keyId" --eab-hmac-key "$$b64MacKey" \
        --agree-tos --email "${service_account_email}" \
        --key-type "ecdsa" --elliptic-curve "secp256r1" \
        --domains "${domain}" --domains "*.${domain}"

        cp -L /etc/letsencrypt/live/${domain}/*.pem .
